# Numpy Lab
Jupyter Notebook adapted from Python file

### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [2]:
np.version.version

'1.16.3'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
#First way
a = np.arange(30).reshape(2,3,5)

#Second way
a = np.empty((2,3,5))

#Third way
a = np.random.rand(2,3,5)

### 4. Print "a"

In [4]:
print(a)

[[[0.63392809 0.04997682 0.00739526 0.8170274  0.50040041]
  [0.54753242 0.4359055  0.16203921 0.04504501 0.28133167]
  [0.21872488 0.87987218 0.67322609 0.46224101 0.97072295]]

 [[0.58926521 0.4642945  0.7614492  0.70441888 0.23080898]
  [0.29505503 0.14566629 0.46469119 0.5139825  0.59539079]
  [0.95550162 0.69702119 0.66535597 0.04768712 0.81950939]]]


### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable "b"

In [5]:
b = np.full((5,3,2), 1)

### 6. Print "b"

In [6]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### 7. Do "a" and "b" have the same size? How do you prove that in Python code?

In [7]:
print("Do 'a' and 'b' have the same size?:", a.size == b.size)

Do 'a' and 'b' have the same size?: True


### 8. Are you able to add "a" and "b"? Why or why not?

In [8]:
#No, beacause arrays have different shapes

### 9. Transpose "b" so that it has the same structure of "a" (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [9]:
c = np.transpose(b)

### 10. Try to add "a" and "c". Now it should work. Assign the sum to variable "d". But why does it work now?

In [10]:
d = a + c #It works because both arrays have the same shape now 

### 11. Print "a" and "d". Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print("Array 'a':\n", a, "\n")

print("Array 'd':\n", d)
#Values of 'd' array equal to values in 'a'+1

Array 'a':
 [[[0.63392809 0.04997682 0.00739526 0.8170274  0.50040041]
  [0.54753242 0.4359055  0.16203921 0.04504501 0.28133167]
  [0.21872488 0.87987218 0.67322609 0.46224101 0.97072295]]

 [[0.58926521 0.4642945  0.7614492  0.70441888 0.23080898]
  [0.29505503 0.14566629 0.46469119 0.5139825  0.59539079]
  [0.95550162 0.69702119 0.66535597 0.04768712 0.81950939]]] 

Array 'd':
 [[[1.63392809 1.04997682 1.00739526 1.8170274  1.50040041]
  [1.54753242 1.4359055  1.16203921 1.04504501 1.28133167]
  [1.21872488 1.87987218 1.67322609 1.46224101 1.97072295]]

 [[1.58926521 1.4642945  1.7614492  1.70441888 1.23080898]
  [1.29505503 1.14566629 1.46469119 1.5139825  1.59539079]
  [1.95550162 1.69702119 1.66535597 1.04768712 1.81950939]]]


### 12. Multiply "a" and "c". Assign the result to "e".

In [12]:
e = a*c

### 13. Does "e" equal to "a"? Why or why not?

In [13]:
e == a
#Yes, because it was multiplied by one

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

### 14. Identify the max, min, and mean values in "d". Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

### 15. Now we want to label the values in "d". First create an empty array "f" with the same shape (i.e. 2x3x5) as d using "np.empty"



In [15]:
f = np.empty([2,3,5])

### 16. Populate the values in f. For each value in "d", if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in "f".
- If a value in "d" is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in "f".
- If a value equals to d_mean, assign 50 to the corresponding value in f"".
- Assign 0 to the corresponding value(s) in "f" for d_min in "d".
- Assign 100 to the corresponding value(s) in "f" for d_max in "d".
- In the end, "f" should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [16]:
#Copy 'd' into 'f'
f = np.copy(d)

#Replace the values
f[f == d_min] = 0
f[f == d_mean] = 50
f[f == d_max] = 100
f[f > d_mean] = 75
f[f < d_mean] = 25

### 17. Print "d" and "f". Do you have your expected "f"?
For instance, if your d is:

        array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
                [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
                [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

               [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],    
                [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],  
                [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your "f" should be:

        array([[[ 75.,  75.,  75.,  25.,  75.],
                [ 75.,  75.,  25.,  25.,  25.],
                [ 75.,  25.,  75.,  75.,  75.]],

               [[ 25.,  25.,  25.,  25., 100.],
                [ 75.,  75.,  75.,  75.,  75.],
                [ 25.,  75.,   0.,  75.,  75.]]])

In [17]:
print("Array 'd':\n", d, "\n")

print("Array 'f':\n", f)

Array 'd':
 [[[1.63392809 1.04997682 1.00739526 1.8170274  1.50040041]
  [1.54753242 1.4359055  1.16203921 1.04504501 1.28133167]
  [1.21872488 1.87987218 1.67322609 1.46224101 1.97072295]]

 [[1.58926521 1.4642945  1.7614492  1.70441888 1.23080898]
  [1.29505503 1.14566629 1.46469119 1.5139825  1.59539079]
  [1.95550162 1.69702119 1.66535597 1.04768712 1.81950939]]] 

Array 'f':
 [[[75. 25. 25. 75. 75.]
  [75. 25. 25. 25. 25.]
  [25. 75. 75. 25. 75.]]

 [[75. 25. 75. 75. 25.]
  [25. 25. 25. 75. 75.]
  [75. 75. 75. 25. 75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements? 
You are expecting the result to be:
    
        array([[[ 'D',  'D',  'D',  'B',  'D'],
                [ 'D',  'D',  'B',  'B',  'B'],
                [ 'D',  'B',  'D',  'D',  'D']],

               [[ 'B',  'B',  'B',  'B',  'E'],
                [ 'D',  'D',  'D',  'D',  'D'],
                [ 'B',  'D',   'A',  'D', 'D']]])
                
Again, you don't need Numpy in this question.

In [ ]:
f[f == 0] = "A"
f[f == 25] = "B"
f[f == 50] = "C"
f[f == 75] = "D"
f[f == 100] = "E"

In [26]:
f[f==75]="a"

TypeError: only size-1 arrays can be converted to Python scalars